AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
    textract-bankslip-reader

Globals:
    Function:
        Timeout: 15
        Runtime: python3.8
        Tracing: Active
        Environment:
            Variables:
                LOG_LEVEL: INFO
                POWERTOOLS_LOGGER_SAMPLE_RATE: 0.1
                POWERTOOLS_LOGGER_LOG_EVENT: true
                POWERTOOLS_METRICS_NAMESPACE: TextractBankSlipReader

Resources:
    BankSlipBucket:
        Type: AWS::S3::Bucket
        DependsOn:
            - BankSlipBucketNotificationTopicPolicy
        Properties:
            BucketName: !Sub textract-bankslip-reader-bankslipbucket-${AWS::AccountId}
            NotificationConfiguration:
                TopicConfigurations:
                    -   Event: s3:ObjectCreated:*
                        Topic: !Ref BankSlipBucketNotificationTopic

    BankSlipBucketNotificationTopic:
        Type: AWS::SNS::Topic

    BankSlipBucketNotificationTopicPolicy:
        Type: AWS::SNS::TopicPolicy
        Properties:
            PolicyDocument:
                Version: '2012-10-17'
                Statement:
                    -   Effect: Allow
                        Principal:
                            Service: s3.amazonaws.com
                        Action: sns:Publish
                        Resource: !Ref BankSlipBucketNotificationTopic
                        Condition:
                            ArnEquals: 
                                aws:SourceArn: !Sub arn:${AWS::Partition}:s3:::textract-bankslip-reader-bankslipbucket-${AWS::AccountId}
            Topics:
                - !Ref BankSlipBucketNotificationTopic

    StartBankSlipAnalysis:
        Type: AWS::Serverless::Function
        Properties:
            Handler: app.start_bankslip_analysis.lambda_handler
            CodeUri: src
            Description: Start Bank Slip Analysis function
            Policies:
                - TextractDetectAnalyzePolicy: {}
                - S3ReadPolicy:
                    BucketName: !Ref BankSlipBucket
            Events:
                BankSlipBucketNotificationEvent:
                    Type: SNS
                    Properties:
                        Topic: !Ref BankSlipBucketNotificationTopic
            Environment:
                Variables:
                    TEXTRACT_NOTIFICATION_TOPIC: !Ref TextractNotificationTopic
                    TEXTRACT_NOTIFICATION_ROLE: !GetAtt TextractNotificationRole.Arn

    TextractNotificationRole:
        Type: AWS::IAM::Role
        Properties:
            AssumeRolePolicyDocument:
                Version: '2012-10-17'
                Statement:
                    -   Effect: Allow
                        Principal:
                            Service: textract.amazonaws.com  
                        Action: sts:AssumeRole
            Policies:
                -   PolicyName: PublishNotification
                    PolicyDocument:
                        Version: '2012-10-17'
                        Statement:
                            -   Effect: Allow
                                Action: sns:Publish
                                Resource: !Ref TextractNotificationTopic

    TextractNotificationTopic:
        Type: AWS::SNS::Topic

    GetBankSlipAnalysis:
        Type: AWS::Serverless::Function
        Properties:
            Handler: app.get_bankslip_analysis.lambda_handler
            CodeUri: src
            Description: Get Bank Slip Analysis function
            Policies:
                - TextractGetResultPolicy: {}
                - SNSPublishMessagePolicy:
                    TopicName: !GetAtt AnalysisResultTopic.TopicName
            Events:
                TextractNotificationEvent:
                    Type: SNS
                    Properties:
                        Topic: !Ref TextractNotificationTopic
            Environment:
                Variables:
                    ANALYSIS_RESULT_TOPIC: !Ref AnalysisResultTopic

    AnalysisResultTopic:
        Type: AWS::SNS::Topic

Outputs:
    BankSlipBucketArn:
        Description: "Bank Slip Bucket ARN"
        Value: !GetAtt BankSlipBucket.Arn

    BankSlipBucketNotificationTopicArn:
        Description: "Bank Slip Bucket Notification Topic ARN"
        Value: !Ref BankSlipBucketNotificationTopic

    StartBankSlipAnalysisFunction:
        Description: "Start Bank Slip Analysis Function ARN"
        Value: !GetAtt StartBankSlipAnalysis.Arn

    TextractNotificationTopicArn:
        Description: "Textract Notification Topic ARN"
        Value: !Ref TextractNotificationTopic

    GetBankSlipAnalysisFunction:
        Description: "Get Bank Slip Analysis Function ARN"
        Value: !GetAtt GetBankSlipAnalysis.Arn

    AnalysisResultTopicArn:
        Description: "Analysis Result Topic ARN"
        Value: !Ref AnalysisResultTopic